[project]
name = "video-calling-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sujan5655", email = "chaudharysujan5655@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.20.0",
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "groq>=1.7.0",
    "psycopg[binary]>=3.3.5",
    "pwdlib[argon2]>=0.3.1",
    "python-dotenv>=1.2.3",
    "python-jose>=3.5.0",
    "sqlalchemy>=2.0.54",
    "uvicorn>=0.53.0",
]

[project.scripts]
video-calling-app = "video_calling_app:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
