from fastapi import FastAPI
import os 
import io
import asyncio
from dotenv import load_dotenv
from fastapi import FastAPI,WebSocket,WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from groq import Groq
from .auth.route import router as auth_router
from .auth.test_route import router as user_router
from .routes.transcription import (
    router as transcription_router,
)
from .routes.signaling import router as signaling_router
#  Load Environment Variables
load_dotenv()
GROQ_API_KEY=os.getenv("GROQ_API_KEY")
if not GROQ_API_KEY:
  raise RuntimeError("GROQ API Key is missing in .env")


# Fast API 
app=FastAPI()

@app.websocket("/ws/test/{room_id}")
async def test_websocket(websocket: WebSocket, room_id: str):
    await websocket.accept()

    print(f"🟢 DIRECT TEST WEBSOCKET CONNECTED: {room_id}")

    try:
        while True:
            message = await websocket.receive_text()

            print(f"📩 DIRECT TEST MESSAGE: {message}")

            await websocket.send_text(
                f"Server received: {message}"
            )

    except WebSocketDisconnect:
        print(
            f"🔴 DIRECT TEST WEBSOCKET DISCONNECTED: {room_id}"
        )
app.include_router(auth_router)
app.include_router(user_router)
app.include_router(transcription_router)
app.include_router(signaling_router)



print("🔥 SIGNALING ROUTER OBJECT:", signaling_router)
print("🔥 SIGNALING ROUTER ROUTES:", signaling_router.routes)

for route in signaling_router.routes:
    print(
        "🔥 ROUTER ROUTE:",
        getattr(route, "path", None),
        getattr(route, "name", None),
    )

print("🔥 MAIN.PY LOADED")
print("🔥 REGISTERED ROUTES:")

print("🔥 MAIN.PY LOADED")
print("🔥 REGISTERED ROUTES:")

for route in app.routes:
    print(
        "TYPE:",
        type(route),
        "REPR:",
        repr(route),
        "PATH:",
        getattr(route, "path", None),
        "NAME:",
        getattr(route, "name", None),
    )


#Cors
app.add_middleware(
  CORSMiddleware,
  allow_origins=[
    "http://localhost:5173",
    "http://localhost:5174"
  ],
  allow_credentials=True,
  allow_methods=["*"],
  allow_headers=["*"]
)


# Groq

groq_client=Groq(
  api_key=GROQ_API_KEY
)




# Test Endpoint
@app.get("/")
async def root():
  return {
    "message":"AI Video Call Backend Running"
  }

# Transcription Feature
# def transcribe_audio(
#     audio_bytes:bytes,
#     language:str|None=None
# ):
#   audio_file=io.BytesIO(audio_bytes)
#   # Tell Groq what type of audio this is
#   audio_file.name = "audio.webm"
 
#   request={
#     "file":audio_file,
#     "model":"whisper-large-v3-turbo",
#     "response_format":"json",
#     "temperature":0.0,
#     "prompt":(
#       "This is a natural conversion"
#       "during a video call."
#       "Transcribe the speech accurately."
#       "Preserve names,technical terms,"
#       "add numbers."
#     )
#   }
  
#   result=groq_client.audio.transcriptions.create(
#     **request
#   )
#   detected_language=getattr(
#     result,"language",None
#   )
#   return {
#     "text":result.text.strip(),
#     "language":detected_language
#   }

from fastapi import Response

from .services.tts import (
    generate_english_speech
)
import asyncio

@app.get("/test-tts")
async def test_tts():

    text = (
        "Hello. This is an English voice "
        "generated by the AI video call system."
    )

    audio = await asyncio.to_thread(
        generate_english_speech,
        text
    )

    return Response(
        content=audio,
        media_type="audio/wav"
    )





@app.get("/debug-routes")
async def debug_routes():
    return [
        {
            "path": getattr(route, "path", None),
            "name": getattr(route, "name", None),
            "type": str(type(route)),
        }
        for route in app.routes
    ]



@app.get("/debug-request/{path:path}")
async def debug_request(path: str):
    print("🔥 DEBUG HTTP PATH:", path)

    return {
        "received_path": path
    }